### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by herpaderpaldent**
This PR contains changes from @5pitf1re and @MichaelErmer from #28 and #27 making style.ci happy. 

# :exclamation: ATTENTION
This package is one of my first work and no testing setup, therefore manual testing is required which i can currently not execute by myself i am fully dependent on the contributors of the changes for the functionality. 
Other then that, i can not guarantee functionality in seat 4.x if it is ever released.

### CODE REVIEW

**Comment by herpaderpaldent** [comment]
@ssfinney and @MichaelErmer would you be able to test the current dev branch in your setup and confirm everything is still functional? 

in `composer.json` change the current entry to 

```
"require": {
        ...
        "herpaderpaldent/seat-discourse": "dev-develop",
        ...
    },
```

**Comment by MichaelErmer** [comment]
Will give it a try tomorrow, apart from that, thanks for your support, I doubt we will upgrade to 4.x in the near future ;)

**Comment by ssfinney** [comment]
I'm pretty sure I'm the wrong guy tagged for this?

However, here's a high-five! ✋ Have a great weekend!

**Comment by herpaderpaldent** [comment]
I should not do this kind of stuff with half a bottle of wine in my system :-P @5pitf1re.

Sorry @ssfinney , have a great weekend to

**Pull request merged**
